### PR TITLE
ovs: drop OVS port's "type" attribute

### PR DESCRIPTION
**Pull request by phoracek**
https://github.com/nmstate/nmstate/pull/525

Signed-off-by: Petr Horacek <phoracek@redhat.com>

### CODE REVIEW

**Comment by phoracek** [comment]
This PR supports https://github.com/nmstate/nmstate/pull/525

**Comment by phoracek** [comment]
@EdDev @cathay4t please take a look

**Comment by EdDev** [comment]
Looks good to me, I think we can merge it when the nmstate PR is merged.

There is one thing that bothers me a bit (only a tiny bit): A user with an older version may read the doc and it will not work for him. Perhaps we should warn in the doc/api that this is correct from version 0.1.1.

**Comment by phoracek** [comment]
@EdDev we can do the same as in oVirt API, have "introduced in" and  "deprecated in" labels.

**edit:** But if we keep "deprecated in" we may also need to keep those parameters in `schema.py`. It becomes a headache. Maybe we should start looking into a way to make the webpage versioned? Or at least parts of it.

**Review by EdDev — APPROVED** [review]
Thanks, please rebase.

**Comment by EdDev** [comment]
@phoracek , a nit, sorry: please use a topic in the commit message.
‘ovs: ....’

**Comment by phoracek** [comment]
@EdDev done

**Review by EdDev — APPROVED** [review]

**Pull request merged**
